// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PixelProje.Dal;

#nullable disable

namespace PixelProje.Dal.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220415222153_uc")]
    partial class uc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PixelProje.Ent.Abone", b =>
                {
                    b.Property<int>("AboneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboneId"), 1L, 1);

                    b.Property<bool>("AboneSituation")
                        .HasColumnType("bit");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Deposit")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboneId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Abone");
                });

            modelBuilder.Entity("PixelProje.Ent.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"), 1L, 1);

                    b.Property<string>("InvoiceAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceAmount")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceTel")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("PixelProje.Ent.Abone", b =>
                {
                    b.HasOne("PixelProje.Ent.Invoice", "Invoice")
                        .WithMany("Abones")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PixelProje.Ent.Invoice", b =>
                {
                    b.Navigation("Abones");
                });
#pragma warning restore 612, 618
        }
    }
}
